# Generated by Django 2.2.2 on 2020-05-08 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
